#!/bin/bash
GIT_HASH="$(git log | head -1 | awk -e '{print $2}' | head -c 12)"
docker buildx build \
--platform linux/386 \
-t scorpio:${GIT_HASH} -f Dockerfile-dev .
docker image tag scorpio:${GIT_HASH} scorpio:latest
