#!/bin/bash
# run the Scorpio Station server in a container

docker run \
--link scorpio_db:scorpio_db \
--name=scorpio_station \
--publish 7777:7777 \
--rm \
-v ${PWD}/config:/scorpio/config:ro \
-v ${PWD}/data:/scorpio/data \
scorpio:latest
