FROM scorpiostation/byond:latest as byond_build

ENV PATH="/byond/bin:${PATH}"

COPY . /scorpio
COPY --from=scorpiostation/scorpio:latest /scorpio/tgui/packages/tgui/public /scorpio/tgui/packages/tgui/public
WORKDIR /scorpio
RUN DreamMaker ci-emerald.dme
