name: 'Check JSON Files'

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  check_json_files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2-beta

    - name: Check JSON Files
      run: './tools/scorpio/check_json_files/action.sh'
