name: 'Compile All Maps'

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  compile_all_maps:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2-beta

    - name: Prepare Maps
      run: './tools/scorpio/compile_all_maps/action.sh'

    - name: Build Emerald
      uses: docker/build-push-action@v2
      with:
        context: .
        file: './tools/scorpio/compile_all_maps/Dockerfile-emerald'
        push: false

    - name: Build MetaStation
      uses: docker/build-push-action@v2
      with:
        context: .
        file: './tools/scorpio/compile_all_maps/Dockerfile-metastation'
        push: false
