name: 'Action'

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  show_map_changes:
    name: "Show Map Changes"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Show Map Changes
      run: './tools/scorpio/show_map_changes/action.sh'
