name: 'Show Map Changes'

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2
      with:
        fetch-depth: 10

    - name: Prepare Build
      run: './tools/scorpio/show_map_changes/action.sh'

    # - name: Show Map Changes
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     file: './tools/scorpio/show_map_changes/Dockerfile'
    #     push: false
