name: "Show Map Changes"

on:
  pull_request:

jobs:
  show_map_changes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2

    - name: Create Map Artifacts
      run: './tools/scorpio/show_map_changes/action.sh'

    - name: Upload Map Artifacts
      if: ${{ env.ARTIFACT_TAG }}
      uses: actions/upload-artifact@v2
      with:
        name: map-artifacts-${{ env.ARTIFACT_TAG }}
        path: artifacts
        retention-days: 7
