name: 'Action'

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  "Show Map Changes":
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Main Branch
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 1
    - name: Checkout PR Branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 100
    - name: Show Map Changes
      run: './tools/scorpio/show_map_changes/action.sh'
